# Generated by Django 4.2.3 on 2024-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gato',
            fields=[
                ('cod_gato', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_gato', models.CharField(max_length=20)),
                ('edad_gato', models.IntegerField()),
                ('raza_gato', models.CharField(max_length=20)),
                ('esterelizacion_gato', models.BooleanField(verbose_name=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
